### ISSUE TITLE
PCMBaseCpp crashes on fedora-clang

### ISSUE THREAD

**Issue by krzbar** [venelin/PCMBaseCpp#2]
PCMBaseCpp crashes on r-devel-linux-x86_64-fedora-clang 
( https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/PCMBaseCpp-00check.html ) causing mvSLOUCH to crash  on r-devel-linux-x86_64-fedora-clang  ( https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/mvSLOUCH-00check.html ). This was brough up by the CRAN team. Is it known what the crash is due to and how is it with the possibilites of fixing it? How should I reply to CRAN?
Thanks
Krzysztof

**Comment by venelin** [comment]
Issue solved and new version (v0.1.9) released on CRAN.
